name: appointment_manager
description: A Appointment Management App for various services provided

publish_to: 'none' 

version: 1.1.0+2

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  url_launcher: ^6.2.2
  timezone: ^0.9.2
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  color: "#F5F5F5"
  image: assets/logo.png
  color_dark: "#1C1F2A"
  image_dark: assets/logo.png

  android_12:
    color: "#F5F5F5"
    image: assets/logo.png
    color_dark: "#1C1F2A"
    image_dark: assets/logo.png